### ISSUE TITLE
Sincerely ask

### ISSUE THREAD

**Issue by dcx950727** [liu-xb/GGL#1]
Hello, I am a student of the School of Telecommunications of Huazhong University of Science and Technology.My name is Chenxi Dong, Postgraduate grade 3.For Creation of graduation thesis,I want to  consult you some questions about your  thesis"Group-Group Loss Based Global-Regional Feature Learning for Vehicle Re-Identiﬁcation "  because my graduation thesis is also about vehicle re-identification.But I have no idea about this.So I want to add you a contact method, please give some guidance,Looking forward and thanks，My wechat and telephone is 13997727818.email is 453215235@qq.com.
Sincere thanks
Best regards
此致敬礼
董晨曦

**Comment by liu-xb** [comment]
We've added each other as friend in wechat, so this issue could be closed. Please feel free to contact me if there is anything I can do for you.
